1. values added: 20
  
2. final result: 20
 
3. values added: 20

4. The code returns a reference error, since result is being called in line 13 which is outside the block it is defined in

5. The code returns a type error. Since result is a constant, it cannot be reassigned to a new value

6. This line is not reached because of the error in line 9. But even if it were reached, it would still return a reference error, since result is out of scope
